// <auto-generated />
using System;
using CareHub.Audit.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace CareHub.Audit.Migrations
{
    [DbContext(typeof(AuditDbContext))]
    [Migration("20260405165645_Initial")]
    partial class Initial
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.4")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("CareHub.Audit.Models.AuditLogEntry", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("ActionType")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)");

                    b.Property<Guid?>("ActorUserId")
                        .HasColumnType("uuid");

                    b.Property<Guid?>("BranchId")
                        .HasColumnType("uuid");

                    b.Property<string>("BrokerMessageId")
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)");

                    b.Property<string>("DetailsJson")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<Guid?>("EntityId")
                        .HasColumnType("uuid");

                    b.Property<string>("EntityType")
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)");

                    b.Property<DateTime>("RecordedAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("BrokerMessageId")
                        .IsUnique()
                        .HasFilter("\"BrokerMessageId\" IS NOT NULL");

                    b.HasIndex("RecordedAt", "Id")
                        .IsDescending(true, true);

                    b.HasIndex("ActionType", "RecordedAt", "Id")
                        .IsDescending(false, true, true);

                    b.HasIndex("ActorUserId", "RecordedAt", "Id")
                        .IsDescending(false, true, true);

                    b.HasIndex("EntityType", "EntityId", "RecordedAt", "Id")
                        .IsDescending(false, false, true, true);

                    b.ToTable("AuditLogEntries");
                });
#pragma warning restore 612, 618
        }
    }
}
